---
name: Deploy to production

on:
  push:
    branches:
      - 'main'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  PROJECT_PATH: .

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL

    steps:
    - name: Checkout game repository
      id: checkout-game-repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache build files
      id: cache-build-files
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-${{ matrix.targetPlatform }}
        restore-keys: Library-

    - name: Build game
      id: build-game
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        unityVersion: 2021.3.16f1
        targetPlatform: ${{ matrix.targetPlatform }}

    - name: Upload build artifact
      id: upload-build-artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build-${{ matrix.targetPlatform }}
        path: build/${{ matrix.targetPlatform }}
